name = "Vinegar Modpack"
author = "Vinegar Community"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c3eb4e326cf3250049b10e7c02f4963cddb3ae2fef412828d2c6e40057974d15"

[versions]
fabric = "0.14.24"
minecraft = "1.19.2"
