name = "Vinegar Modpack"
author = "Vinegar Community"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a7c5ea16f46412c0342a59f10b3ce0d8df97ac16c455b1fef1a68d2f2ed918f2"

[versions]
fabric = "0.14.24"
minecraft = "1.19.4"
