name = "Vinegar Modpack"
author = "Vinegar Community"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8d878ccfb39ec59dbb1a0ea8d87d84fa8ab559b9b04f5fc5ec67cd4e9a1d4dac"

[versions]
fabric = "0.14.24"
minecraft = "1.19.2"
