name = "Vinegar Modpack"
author = "Vinegar Community"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dffad689faab9717d60939d6d7680798b8c64cd6ea720f27891659af67da2264"

[versions]
fabric = "0.14.24"
minecraft = "1.19.2"
