name = "Vinegar Modpack"
author = "Vinegar Community"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1511480a4282974ec677f22403d030b460847d7648f36df51b87ef2fb68fca42"

[versions]
fabric = "0.14.24"
minecraft = "1.19.2"
