name = "Vinegar Modpack"
author = "Vinegar Community"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "489ce330071cbf14bcd3e72e670dc594d411778ac10ee17180c46bd0b3272655"

[versions]
fabric = "0.14.24"
minecraft = "1.19.4"
