name = "Vinegar Modpack"
author = "Vinegar Community"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8440fd4d2c3ccd28daab449f7cfded470d3278b003490a4d45f8dacfbdb73fcd"

[versions]
fabric = "0.14.24"
minecraft = "1.19.2"
