name = "Vinegar Modpack"
author = "Vinegar Community"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b636942df31d2525129afd109b6fd3b886672e6645a81461555be8bac3b44c8c"

[versions]
fabric = "0.14.24"
minecraft = "1.19.2"
