name = "Vinegar Modpack"
author = "Vinegar Community"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9380dd13b7eacab36a3c8361b816a2aeff8ed0af8d61bd26eae84c4746b24ad4"

[versions]
fabric = "0.14.24"
minecraft = "1.19.2"
