name = "Vinegar Modpack"
author = "Vinegar Community"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "67c3ab3f174c524900d739297c6e345ede504ab311c0f16147e200c02aab07ed"

[versions]
fabric = "0.14.24"
minecraft = "1.19.2"
