name = "Vinegar Modpack"
author = "Vinegar Community"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cfbc50c97ab251403f0203df51d20b35587faa060fd36c357e12d45eede4169b"

[versions]
fabric = "0.14.24"
minecraft = "1.19.4"
