name = "Vinegar Modpack"
author = "Vinegar Community"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4f46d93a7949c49e0f46e804dbe14149f90c44ee157f8f21f3fcbd0d15369820"

[versions]
fabric = "0.14.24"
minecraft = "1.19.2"
