name = "Vinegar Modpack"
author = "Vinegar Community"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9c039df355e8e93844971cc3329ae4d52371395aba461fcacc284e690a2979be"

[versions]
fabric = "0.14.24"
minecraft = "1.19.2"
