name = "Vinegar Modpack"
author = "Vinegar Community"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c1c43c8c13e7c070fc988b15e816a979cfb85f76593d234c7badce7c5218a1bb"

[versions]
fabric = "0.14.24"
minecraft = "1.19.2"
