name = "Vinegar Modpack"
author = "Vinegar Community"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "010c6b60f4646d7ba27ea23741f045a47682c9e938613a38d844566aeddfcd8f"

[versions]
minecraft = "1.19.2"
quilt = "0.21.2"
