name = "Vinegar Modpack"
author = "Vinegar Community"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7b1ef79fe8ed051c1de976fe930ddbd9ba4f71933995d2432ff8d2ec4e04ff55"

[versions]
fabric = "0.14.24"
minecraft = "1.19.2"
