name = "Vinegar Modpack"
author = "Vinegar Community"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9d48c61a5730179b4b54ca085dde1f92c83f5d1af263f1fc8ba1422244f847c1"

[versions]
fabric = "0.14.24"
minecraft = "1.19.2"
