name = "Vinegar Modpack"
author = "Vinegar Community"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d7607359e4e6d329181e0b8f20bce88786a31a4926dad6c1e9d757337a5ae94d"

[versions]
fabric = "0.14.24"
minecraft = "1.19.4"
