name = "Vinegar Modpack"
author = "Vinegar Community"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c5a6c2c4320197fcfc5aa03d496879c39e29660705c4a1e576dd8e8e71832908"

[versions]
fabric = "0.14.24"
minecraft = "1.19.2"
