name = "Vinegar Modpack"
author = "Vinegar Community"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "08db90d87a0292c1b0d3b7242c69607fd8a0ce304a534c985efff906c6054932"

[versions]
fabric = "0.14.24"
minecraft = "1.19.2"
