name = "Vinegar Modpack"
author = "Vinegar Community"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c42ccf222885fe41f68e9abb6c8054a0559e73fbe1f57357cf23181dcdc103ab"

[versions]
fabric = "0.14.24"
minecraft = "1.19.2"
