name = "Vinegar Modpack"
author = "Vinegar Community"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e853a1fd99991cc1b66d2d6ff78ead7652860aa4986078c02ceb46c0824645db"

[versions]
fabric = "0.14.24"
minecraft = "1.19.2"
