name = "Vinegar Modpack"
author = "Vinegar Community"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8bbdad27c8f891340aa14fc3d9f973bfe8ead06e912800e0cc454fabc35792c6"

[versions]
fabric = "0.14.24"
minecraft = "1.19.2"
