name = "Vinegar Modpack"
author = "Vinegar Community"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a7b2a21006f48326b145df7019edabd0872d651514639ecf9a4522ca11ba5d97"

[versions]
fabric = "0.14.24"
minecraft = "1.19.2"
