name = "Vinegar Modpack"
author = "Vinegar Community"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e4487eb638a1f03d76dcc531cdec7ce4379123f3d2987e50bd902b1b6701389f"

[versions]
fabric = "0.14.24"
minecraft = "1.19.2"
