name = "Vinegar Modpack"
author = "Vinegar Community"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fa6fb5dcdb32fecd853d5cf9c335921c59ab46bd5718c0cc9ff348f059144bee"

[versions]
fabric = "0.14.24"
minecraft = "1.19.2"
