name = "Vinegar Modpack"
author = "Vinegar Community"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1dab769bb3b1fb2f39a0d73646510f40bb84b3f988cee1164521539b1feaf549"

[versions]
fabric = "0.14.24"
minecraft = "1.19.2"
