name = "Vinegar Modpack"
author = "Vinegar Community"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "13cb39968ad7065e0b4d1293252932f01a1746556bc89944cf40a9929ab88b1f"

[versions]
fabric = "0.14.24"
minecraft = "1.19.2"
