name = "Vinegar Modpack"
author = "Vinegar Community"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "474bd705c59a6602132e5a75cf1d38d4fd407f15dacb2f59d61d51cd327d7a7c"

[versions]
fabric = "0.14.24"
minecraft = "1.19.2"
